# Generated by Django 4.1.1 on 2022-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=75)),
                ('lastname', models.CharField(max_length=75, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=75)),
                ('password_confirm', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
