# Generated by Django 4.1.1 on 2022-10-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_offered', to='rentxapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rented_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_rental', to='rentxapp.product')),
                ('rentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to='rentxapp.user')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='rentxapp.user')),
            ],
        ),
    ]
