# Generated by Django 4.1.1 on 2022-10-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rentxapp.category'),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rented_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentxapp.product'),
        ),
    ]
