# Generated by Django 4.1.1 on 2022-10-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0004_remove_category_products_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inrenting', to='rentxapp.product'),
        ),
    ]
