# Generated by Django 4.1.1 on 2022-10-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0005_alter_rental_rented_product'),
        ('rentxapp', '0006_remove_user_password_confirm'),
    ]

    operations = [
    ]
