# Generated by Django 4.1.1 on 2022-10-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0010_alter_category_id_alter_product_id_alter_rental_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inrenting', to='rentxapp.product'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_rentals', to='rentxapp.user'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_rentals', to='rentxapp.user'),
        ),
    ]
