# Generated by Django 4.1.1 on 2022-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentxapp', '0011_alter_rental_rented_product_alter_rental_rentee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_products', to='rentxapp.user'),
        ),
    ]
